---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/iconUrl: img/icons/camel.svg
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    app: camel-ose-springboot-xml
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: org.mycompany
  name: camel-ose-springboot-xml
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: camel-ose-springboot-xml
    provider: fabric8
    group: org.mycompany
