package com.siebel.asi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-03-01T19:20:32.832+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://siebel.com/asi/", name = "Default")
@XmlSeeAlso({com.siebel.xml.order_20interface.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Default {

    @WebMethod(operationName = "TMCVVORPlantCodeUpdate", action = "document/http://siebel.com/asi/:TMCVVORPlantCodeUpdate")
    @WebResult(name = "TMCVVORPlantCodeUpdate_Output", targetNamespace = "http://siebel.com/asi/", partName = "TMCVVORPlantCodeUpdate_Output")
    public TMCVVORPlantCodeUpdateOutput tmcvvorPlantCodeUpdate(
        @WebParam(partName = "TMCVVORPlantCodeUpdate_Input", name = "TMCVVORPlantCodeUpdate_Input", targetNamespace = "http://siebel.com/asi/")
        TMCVVORPlantCodeUpdateInput tmcvvorPlantCodeUpdateInput
    );
}
